# -*- coding: utf-8 -*-
"""ASSESLY.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/18iELkuvKD_dSyKnPlWDBYc831-GgPXwS
"""

import pandas as pd
import plotly.express as px

import numpy as np
import pandas as pd
from matplotlib import pyplot as plt
from sklearn.cluster import KMeans
from sklearn.preprocessing import StandardScaler

"""# Import data """

# import data from xlsx to dataframe

student_result_maths = pd.read_excel (r'/content/StudentResult_Mathematics.xlsx')
student_result_science = pd.read_excel (r'/content/StudentResult_Science.xlsx')
student_result_sejarah = pd.read_excel (r'/content/StudentResult_Sejarah.xlsx')

student_result_maths

"""# Clustering"""

# get column for clustering
data = student_result_maths[['Quiz','Final']]

# apply standard scalar on data
ss = StandardScaler()
X = ss.fit_transform(data)

#fit data into model
model = KMeans(n_clusters=4, verbose=0)
result = model.fit_predict(X)

#get the label
student_result_maths['Performance Group'] = result.tolist()
student_result_maths['Performance Group'] = student_result_maths['Performance Group'].apply(str)
student_result_maths['Performance Group'].replace({"0": "A", "1": "B", "2": "C", "3": "D"}, inplace=True)

fig = px.scatter(student_result_maths, x="Quiz", y="Final",color="Performance Group", hover_data=['Student Name','Quiz'])
fig.update_traces(marker={'size': 10})    

fig.show()

"""## Clustering function"""

def getClustering(df,c1,c2):
  # get column for clustering
  data = df[[c1,c2]]

  # apply standard scalar on data
  ss = StandardScaler()
  X = ss.fit_transform(data)

  #fit data into model
  model = KMeans(n_clusters=4, verbose=0)
  result = model.fit_predict(X)

  #get the label
  df['Performance Group'] = result.tolist()
  df['Performance Group'] = df['Performance Group'].apply(str)
  df['Performance Group'].replace({"0": "A", "1": "B", "2": "C", "3": "D"}, inplace=True)

  #display
  fig = px.scatter(df, x=c1, y=c2,color="Performance Group", hover_data=['Student Name',c1])
  fig.update_traces(marker={'size': 10})    

  fig.show()

#testing pass data
dataset = student_result_sejarah #@param [student_result_sejarah, student_result_science, student_result_maths] {type:"raw"}


feature1 = 'E3' #@param ["E1", "E2", "E3", "Final", "Quiz", "Attendance"]
feature2 = 'Final' #@param ["E1", "E2", "E3", "Final", "Quiz", "Attendance"]

# call function
getClustering(dataset,feature1,feature2)